const colorVar = (name) => `rgb(var(--token-color-${name}-rgb) / <alpha-value>)`;
const tokenVar = (name) => `rgb(var(--token-${name}-rgb) / <alpha-value>)`;

module.exports = {
  theme: {
    extend: {
      colors: {
        bg: tokenVar('bg-base'),
        surface: tokenVar('bg-surface'),
        muted: tokenVar('bg-muted'),
        border: tokenVar('border-default'),
        ring: tokenVar('focus-ring'),
        danger: tokenVar('danger-base'),
        accent: 'rgb(var(--token-accent-primary-rgb) / <alpha-value>)',
        'accent-secondary': 'rgb(var(--token-accent-secondary-rgb) / <alpha-value>)',
        'accent-tertiary': 'rgb(var(--token-accent-tertiary-rgb) / <alpha-value>)',
        'text-primary': 'rgb(var(--token-text-primary-rgb) / <alpha-value>)',
        'text-inverse': tokenVar('text-inverse'),
        'text-muted': tokenVar('text-muted'),
        'deep-pink': colorVar('deep-pink'),
        'teal': colorVar('teal'),
        'sun-red': colorVar('sun-red'),
        'brand-black': colorVar('brand-black'),
        'brand-white': colorVar('brand-white'),
        'off-white': colorVar('off-white'),
        'navy-bg': colorVar('navy-bg'),
        'purple': colorVar('purple'),
        'red-dot': colorVar('red-dot'),
        'yellow-river': colorVar('yellow-river'),
        'mint-text': colorVar('mint'),
        'light-gray': colorVar('light-gray'),
        'industrial-gold': colorVar('industrial-gold'),
        'industrial-rust': colorVar('industrial-rust'),
        'industrial-iron': colorVar('industrial-iron'),
        'historic-sepia': colorVar('historic-sepia'),
        'historic-cream': colorVar('historic-cream'),
        'historic-dark': colorVar('historic-dark'),
        'insight-cyan': colorVar('insight-cyan'),
        'insight-blue': colorVar('insight-blue'),
        'fund-green': colorVar('fund-green'),
        'refund-amber': colorVar('refund-amber'),
        'cancelled-red': colorVar('cancelled-red'),
        'thermal-orange': colorVar('thermal-orange'),
        'heat-amber': colorVar('heat-amber'),
        'compute-blue': colorVar('compute-blue'),
        'grid-green': colorVar('grid-green'),
        'solar-yellow': colorVar('solar-yellow'),
        'night-purple': colorVar('night-purple'),
        'steel-gray': colorVar('steel-gray'),
        'copper-warm': colorVar('copper-warm'),
        'oil-dark': colorVar('oil-dark'),
        'luck-accent': colorVar('luck-accent'),
        'luck-accent2': colorVar('luck-accent2'),
        'luck-warn': colorVar('luck-warn'),
        'luck-bad': colorVar('luck-bad'),
      },
      fontFamily: {
        display: ['var(--token-font-display)', 'serif'],
        mono: ['var(--token-font-mono)', 'monospace'],
        accent: ['var(--token-font-accent)', 'cursive'],
        futuristic: ['var(--token-font-futuristic)', 'sans-serif'],
        stylish: ['var(--token-font-display)', 'serif'],
        terminal: ['var(--token-font-mono)', 'monospace'],
        erratic: ['var(--token-font-accent)', 'cursive'],
      },
    },
  },
};
